---
server.port: 8080
spring:
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /graphql
  data.mongodb:
    host: localhost
    port: 27017
    database: graphql-training
    auto-index-creation: true
---
spring.config.activate.on-profile: docker
spring.data.mongodb.host: mongodb